flowchart TD
    A[Property] --> B{Are units associated with the result values?}
    B --> |false|C{Are the result values binary?}
    B --> |true|D[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT1.mmd'>DT1</a><br> quantitative property] 
    C --> |false|E{Are the result values ordinary?}
    C --> |true|H[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP12.yaml'>VDP12</a><br> new qualitative variable] 
    E --> |true|F[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP11.yaml'>VDP11</a><br> existing <br> qualitative variable] 
    E --> |false|H

