---
title: PROPERTY UNITLESS
---
flowchart TD
    A[Check observation results <br> or description] --> B{Are units associated <br> with the result values? <br> percentage is not a unit}:::white
    
    %% Branch: Units Present -> QUANTITY (Ratio Scale with Units)
    B --> |true|N[QUANTITY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT2.mmd'>DT2</a><br>]
    
    %% Branch: Unitless Path
    B --> |false|C{Are the results categorical <br> or quantitative?}:::white
    
    %% Categorical Branch (Binary, Nominal, Ordinal)
    C -- categorical --> D{Which categorical <br> scale applies?}:::white
    D -- binary --> E[BOOLEAN <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP103.yaml'>VDP103</a><br>]
    D -- nominal -->F[NOMINAL <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP101.yaml'>VDP101</a><br>]
    D -- ordinal -->G[ORDINAL <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP102.yaml'>VDP102</a><br>]
    C -- quantitative -->H{Which quantitative <br> scale applies?}:::white
    H -- natural-numbers -->I{Normalized?}:::white
    I --> |true|Q[NORMALIZED COUNT <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP124.yaml'>VDP124</a><br>]
    I --> |false|P[COUNT <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP104.yaml'>VDP104</a><br>]
    H -- non-count-discrete -->O[DISCRETE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP104.yaml'>VDP105</a><br>]
    H -- time-instant -->K[INSTANT <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP137.yaml'>VDP137</a><br>]
    H -- continuous-intermediates -->L[INTERVAL <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP138.yaml'>VDP138</a><br>]
    H -- ratio -->M[DECIMAL VALUE UNITLESS <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT1.mmd'>DT1</a><br>]

    classDef blue fill:#90D5FF
    classDef satblue fill:#57B9FF
    classDef white fill:#f3f6f4
    classDef green fill:#6aa84f
