---
title: DECIMAL VALUE UNITLESS
---
flowchart TD
    A[PROPERTY DERIVED <br> FROM RATIO/PHYSICAL RELATIONSHIP] --> B{Is it calculated from comparing the same physical quantity?}:::white
    B --> |false|C[INDEX <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP25.yaml'>VDP25</a>]
    B --> |true|D{Can the value exceed 1.0?}:::white
    D --> |false|E{Comparing two areas?}:::white
    D --> |true|L{Does the number describe a static spatial geometry?}:::white
    E --> |true|G[COVER <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP15.yaml'>VDP15</a>]
    E --> |false|H[FRACTION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP21.yaml'>VDP21</a>]
    L --> |true|M[GEOMETRIC RATIOS <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP04.yaml'>VDP04</a>] 
    L --> |false|N[TRANSPORT/INTERACTION COEFFICIENT <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP05.yaml'>VDP05</a>]
   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF 
   classDef white fill:#f3f6f4
   classDef green fill:#6aa84f
