flowchart TD
    A[Quantitative Property] --> B(Is it a composed term?)
    B --> C{true}
    B --> D{false}
    C --> E(Does concept exist?) 
    E --> F{true}
    E --> G{false}
    F --> H(Numerator a mass unit?)
    D --> I{VDP13} 
    G --> J(VDP13)
    H --> L{true}
    L --> M(Mass concentration)
    H --> N{false}
    N --> O(VDP13)
