flowchart TD
    A[Quantitative Property] --> B{Is it a fundamental quantity?}
    B --> |true|C(fundamental quantity)
    B --> |false|D[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT2.mmd'>Derived property <br> DT2</a>] 

