---
title: CONSTRAINT on STATISTICAL MODIFIER
---
flowchart TD
    A(PROPERTY)  --> B{Providing time-specific <br> information?}:::white
    B --> |true|C{Specifying the <br> integration interval?}:::white
    B --> |false|G{Providing space-specific <br> information}:::white
    C --> |false|D{Is it specifying <br> the sampling frequency?}:::white
    C --> |true|E[INTERVAL <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP89.yaml'>VDP89</a>]:::rose
    D --> |true|F[SAMPLING FREQUENCY<br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP66.yaml'>VDP66</a>]:::rose
    G --> |true|H{Is it specifying <br> a required <br> spatial extent?}:::white
    H --> |false|I{Is it specifying <br> a required <br> spatial distribution?}:::white
    H --> |true|K[SPATIAL EXTENT <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP74.yaml'>VDP74</a>]:::rose
    I --> |true|L[SPATIAL DISTRIBUTION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP80.yaml'>VDP80</a>]:::rose

   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF 
   classDef white fill:#f3f6f4
   classDef green fill:#6aa84f
   classDef rose fill:#ea9999
