flowchart TD
    A[Physical Quantity] --> B(A ratio?<br>check the unit)
    B --> |true|C(ASYMMETRIC SYSTEM in the Object of Interest. <br> Time in the denominator?) 
    B --> |false|D[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP13.yaml'>VDP13</a>]
    C --> |true|E(Rate <br> is it a flux? <br> mass per area per time?)
    C --> |false|D
    E --> |true|F(is the area constrained?)
    E --> |false|D
    F --> |true|G[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP23.yaml'>VDP23</a>](FLUX COMPLEX)
