flowchart TD
    A[Physical Quantity] --> B(Is it a ratio?<br>check the unit)
    B --> |true|C(Amount of substance <br> in a medium?) 
    B --> |false|D[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP13.yaml'>VDP13</a>]
    C --> |true|E(A fundamental <br> physical quantity?)
    C --> |false|D
    E --> |true|F[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP10.yaml'>VDP10</a>]
    E --> |false|D
