---
title: PROPERTY DERIVED
---
flowchart TD
    A[Derived quantitative <br> property] --> B{A ratio?<br>check the units}:::white
    B --> |true|N{Time in the denominator?}:::white
    B --> |false|I[RATIOLESS DERIVED <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP20.yaml'>VDP20</a>]
    N --> |true|E{Measure of an occurrence?}:::white
    E --> |false|K[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT4.mmd'>FLUX DT4</a>]
    E --> |true|J(Event rate)
    N --> |false|O{Involving different <br> quantities?}:::white
    O --> |true|P[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT5.mmd'>RATIO DT5</a>]
    O --> |false|Q{Involving different <br> physical entities?}:::white
    Q --> |false|R{Is it a scalar ratio?}:::white
    R --> |true|L[ANGLE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP03.yaml'>VDP03</a>]
    R --> |false|M[DIRECTION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP03.yaml'>VDP03</a>]
    Q --> |true|S[FRACTION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP21.yaml'>VDP21</a>]
   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF 
   classDef white fill:#f3f6f4
   classDef green fill:#6aa84f

