---
title: PROPERTY DERIVED
---
flowchart TD
    A[Derived quantitative <br> property] --> AB{Is it an intrinsic, <br> inherent characteristic?}:::white
    AB --> |true|U[INTRINSIC <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP126.yaml'>VDP126</a>]
    AB --> |false|ABB{Is the unit atomic derived?}:::white
    ABB --> |true|Z[ATOMIC DERIVED <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP126.yaml'>VDP126</a>]
    ABB --> |false|B{Is the unit a ratio?<br>Check the units}:::white
    B --> |true|N{Time in the denominator?}:::white
    B --> |false|C{Is it a property <br> of a property?}:::white
    C --> |true|D{Is involving a <br> statistical measure?}:::white
    D --> |true|G[STATISTICAL PROPERTY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP136.yaml'>VDP136</a>]
    D --> |false|F[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT2.mmd'>DT1</a>]
    C --> |false|I{Is it normalized?}:::white
    I --> |true|T[NORMALIZED <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP115.yaml'>VDP115</a>]
    I --> |false|U[RATIOLESS DERIVED <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP114.yaml'>VDP114</a>]
    N --> |true|E{Measure of an occurrence?}:::white
    E --> |false|K[FLUX <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT4.mmd'> DT4</a>]
    E --> |true|J[EVENT RATE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP118.yaml'>VDP118</a>]
    N --> |false|O{Involving different <br> quantities?}:::white
    O --> |true|P[RATIO <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/Decisition_trees/DT5.mmd'> DT5</a>]
    O --> |false|Q{Involving different <br> physical entities?}:::white
    Q --> |false|R{Is one of the two <br> an external reference?}:::white
    R --> |true|L[ANGLE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP116.yaml'>VDP116</a>]
    R --> |true|M[DIRECTION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP117.yaml'>VDP117</a>]
    Q --> |true|S{Is it cover?}:::white
    S --> |true|X[COVER <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP111.yaml'>VDP111</a>]
    S --> |false|V[FRACTION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP110.yaml'>VDP110</a>]
   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF 
   classDef white fill:#f3f6f4
   classDef green fill:#6aa84f

