---
title: PROPERTY RATIO
---
flowchart TD
    A[Ratio without time <br> different quantities] --> B{Is it a mixture?}:::white
    B --> |true|D{Is the deonminator area?}:::white
    B --> |false|M[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP20.yaml'>VDP20</a>]
    D -- |false|T[CONCENTRATION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP17.yaml'>VDP17</a>]
    D -- |true|C[AERIC <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP14.yaml'>VDP14</a>]
   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF 
   classDef white fill:#f3f6f4
   classDef green fill:#6aa84f
