---
title: PROPERTY RATIO - OBJECT OF INTEREST
---
flowchart TD
    A[Ratio without time <br> different quantities] --> B{What is the <br> denominator?}:::white
    B -- Area -->C[AREAL DENSITY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP27.yaml'>VDP27</a>]
    B -- Entity -->F[ENTITY DENSITY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP24.yaml'>VDP24</a>]
    B -- Length -->D[LINEIC DENSITY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP23.yaml'>VDP23</a>]
    B -- Mass -->E{What is the <br> numerator?}:::white
    E -- Entity --> L[MASSIC NUMBER DENSITY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP21.yaml'>VDP21</a>]
    E -- Amount of Substance --> P[MASSIC AMOUNT OF <br> SUBSTANCE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP22.yaml'>VDP22</a>]
    B -- Volume -->G{Is it a mixture <br> of substances?}:::white
    G --> |false|H[VOLUMIC DENSITY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP26.yaml'>VDP26</a>]
    G--> |true|J{Is it count per volume?}:::white
    J --> |true|I[VOLUMIC NUMBER DENSITY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP25.yaml'>VDP25</a>]
    J --> |false|M[CONCENTRATION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP28.yaml'>VDP28</a>]
    I --> N
    C --> N[RATIO <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP35.yaml'>VDP35</a>]:::satblue
    F --> N
    D --> O[SINGLE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP33.yaml'>VDP33</a>]:::satblue
    H --> O
    L --> N
    P --> N
    M --> N
   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF 
   classDef white fill:#f3f6f4
   classDef green fill:#6aa84f
