---
title: PROPERTY - OBJECT OF INTEREST - MATRIX
---
flowchart TD
    A[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP16.yaml'>LENGTH <br> VDP16</a>] --> C[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP28.yaml'>SINGLE OBJECT <br> VDP28</a>]:::satblue
    B[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP10.yaml'>FUNDAMENTAL <br> VDP10</a>]  --> C
    D[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP20.yaml'>RATIOLESS DERIVED <br> VDP20</a>] --> C
    E[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP20.yaml'>FLUX SIMPLIFIED <br> VDP26</a>] --> C
    I[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP23.yaml'>FLUX COMPLEX <br> VDP23</a>] --> F  
    M[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP17.yaml'>CONCENTRATION <br> VDP17</a>] --> F
    L[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP21.yaml'>MASS FRACTION <br> VDP21</a>] --> F[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP26.yaml'>RATIO <br> VDP26</a>]:::satblue
    Q[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP18.yaml'>FLUX SIMPLE <br> VDP18</a>] --> C
    P[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP15.yaml'>COVER <br> VDP15</a>] --> F
    Q --> K[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP34.yaml'>MATRIX: FLOW <br> VDP34</a>]:::blue
    G[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP23.yaml'>DISTANCE <br> VDP19</a>] --> F 
    G --> R[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP30.yaml'>TWO EQUAL <br> VDP30</a>]:::satblue
    I --> K

   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF
