---
title: PROPERTY - OBJECT OF INTEREST
---
flowchart TD
    A[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP16.yaml'>Length <br> VDP16</a>] --> C[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP16.yaml'>SINGLE OBJECT <br> VDP28</a>]
    B[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP10.yaml'>FUNDAMENTAL <br> VDP10</a>]  --> C
    D[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP10.yaml'>RATIOLESS DERIVED <br> VDP20</a>] --> C
    E[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP10.yaml'>MASS FRACTION <br> VDP21</a>] --> F[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP16.yaml'>RATIO <br> VDP26</a>]
    G[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP10.yaml'>CONCENTRATION <br> VDP17</a>] --> F
