---
title: PROPERTY - OBJECT OF INTEREST - MATRIX
---
flowchart TD
    A[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP16.yaml'>LENGTH <br> VDP16</a>] --> C[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP28.yaml'>SINGLE OBJECT <br> VDP28</a>]:::satblue
    B[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP10.yaml'>FUNDAMENTAL <br> VDP10</a>]  --> C
    D[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP20.yaml'>RATIOLESS DERIVED <br> VDP20</a>] --> C
    L[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP21.yaml'>MASS FRACTION <br> VDP21</a>] --> F[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP26.yaml'>RATIO <br> VDP26</a>]:::satblue
    M[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP17.yaml'>CONCENTRATION <br> VDP17</a>] --> F
    H[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP18.yaml'>FLUX SIMPLE <br> VDP18</a>] --> C
    I[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP23.yaml'>FLUX COMPLEX <br> VDP23</a>] --> F
    N[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP13.yaml'>DENSITY SIMPLE <br> VDP13</a>] --> C
    O[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP14.yaml'>DENSITY <br> VDP14</a>] --> F
    P[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP15.yaml'>DENSITY <br> VDP15</a>] --> F
    I --> K[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP34.yaml'>MATRIX: FLOW <br> VDP34</a>]:::blue

   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF
