---
title: PROPERTY - OBJECT OF INTEREST - MATRIX
---
flowchart TD
    A[LENGTH <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP106.yaml'> VDP106</a>] --> C[SINGLE<br><a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP33.yaml'> VDP33</a>]:::satblue
    B[FUNDAMENTAL <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP109.yaml'> VDP109</a>]  --> C
    D[RATIOLESS DERIVED <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP114.yaml'> VDP114</a>] --> C
    E[FLUX SIMPLIFIED <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP129.yaml'>VDP129</a>] --> C
    I[FLUX COMPLEX <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP131.yaml'>VDP131</a>] --> F  
    M[CONCENTRATION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP128.yaml'>VDP128</a>] --> F
    L[FRACTION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP110.yaml'>VDP110</a>] --> F[<a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP35.yaml'>RATIO <br> VDP35</a>]:::satblue
    Q[FLUX SIMPLE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP130.yaml'>VDP130</a>] --> C
    P[COVER <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP111.yaml'>VDP111</a>] --> F
    Q --> K[MATRIX: FLOW <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP45.yaml'>VDP45</a>]:::blue
    G[DISTANCE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP108.yaml'>VDP108</a>] --> F 
    G --> R[TWO EQUAL <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP34.yaml'>VDP34</a>]:::satblue
    I --> K

   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF
