---
title: CONSTRAINT
---
flowchart TD
    A(ENTITY):::satblue  --> AB{Specifying its nature?}:::white
    AB --> |true|B{A specific type?}:::white
    AB --> |false|E{Specifying how its <br> constitution?}:::white
    B --> |true|C[TYPE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP65.yaml'>VDP65</a>]:::rose
    B --> |false|D{Is the entity a human?}:::white
    D --> |true|F[ROLE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP89.yaml'>VDP89</a>]:::rose
    E --> |true|F{:::rose
   
   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF 
   classDef white fill:#f3f6f4
   classDef green fill:#6aa84f
   classDef rose fill:#ea9999
