---
title: CONSTRAINT on PROPERTY
---
flowchart TD
    A(PROPERTY)  --> B{Specifying its type?}:::white
    B --> |true|C[TYPE <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP65.yaml'>VDP65</a>]:::rose
    B --> |false|D{Is it specifying its <br> condition?}:::white
    D --> |true|E[CONDITION <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP70.yaml'>VDP70</a>]:::rose
    D --> |false|F{Is it specifying <br> a required <br> reference point?}:::white
    F --> |true|G[DATUM <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP68.yaml'>VDP68</a>]:::rose
    F --> |false|IH{Is it providing <br> interpretation help?}:::white
    IH --> |true|HI{Is it defining it?}:::white
    HI --> |true|HK[DEFINING ENTITY <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP85.yaml'>VDP85</a>]:::rose
    HI --> |false|I[Interpretation <br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP73.yaml'>VDP73</a>]:::rose
    A --> J{Specifing the <br> cause?}:::white
    J --> |true|K[CAUSE<br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP72.yaml'>VDP72</a>]:::rose
    J --> |false|L{Does it provide <br> time-specific info?}:::white
    L --> |true|M{A time point?}:::white
    L --> |false|T{Does it provide <br> spatial info?}:::white
    M --> |true|N[TIME<br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP78.yaml'>VDP78</a>]:::rose
    M --> |false|O{A time extent?}:::white
    O --> |true|Q[TEMPORAL EXTENT<br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP75.yaml'>VDP75</a>]:::rose
    O --> |false|R{Reporting frequency?}:::white
    R --> |true|S[REPORTING FREQUENCY<br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP83.yaml'>VDP83</a>]:::rose
    T --> |true|U{Spatial Extent?}:::white
    U --> |true|V[SPATIAL EXTENTY<br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP.75yaml'>VDP75</a>]:::rose
    U --> |false|W[SPATIAL DISTRIBUTION<br> <a href='https://github.com/mabablue/I-ADOPT-patterns-playground/blob/main/pattern/VDP.80yaml'>VDP80</a>]:::rose
   classDef blue fill:#90D5FF
   classDef satblue fill:#57B9FF 
   classDef white fill:#f3f6f4
   classDef green fill:#6aa84f
   classDef rose fill:#ea9999
